use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::{FixtureName, FixtureProfile};

/// Machine-readable manifest for one provisioned fixture file.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FixtureFileManifest {
    /// Stable source id containing this file.
    pub source_id: String,
    /// Forward-slash relative path inside the source root.
    pub relative_path: String,
    /// SHA-256 digest of the exact generated bytes.
    pub sha256: String,
    /// Whether the file is a supported audio input.
    pub supported_audio: bool,
    /// Channel count for generated WAV files.
    pub channels: Option<u16>,
    /// Sample rate for generated WAV files.
    pub sample_rate: Option<u32>,
    /// Exact frame count for generated WAV files.
    pub frames: Option<u32>,
}

/// Machine-readable manifest for one configured fixture source.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FixtureSourceManifest {
    /// Stable logical source id.
    pub source_id: String,
    /// Stable source directory name below the fixture root.
    pub directory_name: String,
    /// Resolved source root for this provisioned run.
    pub root: PathBuf,
    /// Expected relative directories, including deliberately empty folders.
    pub directories: Vec<String>,
    /// Number of supported source files.
    pub supported_file_count: usize,
    /// Number of unsupported/non-audio files.
    pub unsupported_file_count: usize,
    /// Expected per-file and per-source readiness targets after discovery.
    pub expected_readiness_target_count: usize,
}

/// Complete deterministic native-source fixture manifest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FixtureManifest {
    /// Fixture contract version.
    pub fixture_version: u32,
    /// Stable fixture name.
    pub fixture: FixtureName,
    /// Stable deterministic generation seed.
    pub deterministic_seed: u64,
    /// Non-live profile populated by this provision.
    pub profile: FixtureProfile,
    /// Resolved profile root containing config and global library state.
    pub profile_path: PathBuf,
    /// Resolved disposable fixture root.
    pub fixture_root: PathBuf,
    /// Configured source manifests.
    pub sources: Vec<FixtureSourceManifest>,
    /// Exact generated input files and content hashes.
    pub files: Vec<FixtureFileManifest>,
    /// Total supported file count across all sources.
    pub expected_supported_file_count: usize,
    /// Total unsupported/non-audio file count across all sources.
    pub expected_unsupported_file_count: usize,
    /// Total readiness target count after authoritative discovery.
    pub expected_readiness_target_count: usize,
}
