//! Keyboard input primitives used by hotkeys and future GUI backends.

/// Backend-agnostic key code values used by sempal hotkeys.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) enum KeyCode {
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    A,
    B,
    C,
    D,
    Enter,
    F,
    F1,
    G,
    I,
    L,
    M,
    N,
    OpenBracket,
    CloseBracket,
    P,
    Quote,
    R,
    S,
    Slash,
    Backslash,
    T,
    U,
    W,
    X,
    Y,
    Z,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
}

/// Convert an `egui` key into the local backend-agnostic key representation.
pub(crate) fn key_code_from_egui(key: egui::Key) -> Option<KeyCode> {
    Some(match key {
        egui::Key::Num0 => KeyCode::Num0,
        egui::Key::Num1 => KeyCode::Num1,
        egui::Key::Num2 => KeyCode::Num2,
        egui::Key::Num3 => KeyCode::Num3,
        egui::Key::Num4 => KeyCode::Num4,
        egui::Key::Num5 => KeyCode::Num5,
        egui::Key::Num6 => KeyCode::Num6,
        egui::Key::Num7 => KeyCode::Num7,
        egui::Key::Num8 => KeyCode::Num8,
        egui::Key::Num9 => KeyCode::Num9,
        egui::Key::A => KeyCode::A,
        egui::Key::B => KeyCode::B,
        egui::Key::C => KeyCode::C,
        egui::Key::D => KeyCode::D,
        egui::Key::Enter => KeyCode::Enter,
        egui::Key::F => KeyCode::F,
        egui::Key::F1 => KeyCode::F1,
        egui::Key::G => KeyCode::G,
        egui::Key::I => KeyCode::I,
        egui::Key::L => KeyCode::L,
        egui::Key::M => KeyCode::M,
        egui::Key::N => KeyCode::N,
        egui::Key::OpenBracket => KeyCode::OpenBracket,
        egui::Key::CloseBracket => KeyCode::CloseBracket,
        egui::Key::P => KeyCode::P,
        egui::Key::Quote => KeyCode::Quote,
        egui::Key::R => KeyCode::R,
        egui::Key::S => KeyCode::S,
        egui::Key::Slash => KeyCode::Slash,
        egui::Key::Backslash => KeyCode::Backslash,
        egui::Key::T => KeyCode::T,
        egui::Key::U => KeyCode::U,
        egui::Key::W => KeyCode::W,
        egui::Key::X => KeyCode::X,
        egui::Key::Y => KeyCode::Y,
        egui::Key::Z => KeyCode::Z,
        egui::Key::ArrowLeft => KeyCode::ArrowLeft,
        egui::Key::ArrowRight => KeyCode::ArrowRight,
        egui::Key::ArrowUp => KeyCode::ArrowUp,
        egui::Key::ArrowDown => KeyCode::ArrowDown,
        _ => return None,
    })
}

/// Convert a `winit` physical key code into the local backend-agnostic key representation.
pub(crate) fn key_code_from_winit(key: winit::keyboard::KeyCode) -> Option<KeyCode> {
    use winit::keyboard::KeyCode as WinitKeyCode;
    Some(match key {
        WinitKeyCode::Digit0 => KeyCode::Num0,
        WinitKeyCode::Digit1 => KeyCode::Num1,
        WinitKeyCode::Digit2 => KeyCode::Num2,
        WinitKeyCode::Digit3 => KeyCode::Num3,
        WinitKeyCode::Digit4 => KeyCode::Num4,
        WinitKeyCode::Digit5 => KeyCode::Num5,
        WinitKeyCode::Digit6 => KeyCode::Num6,
        WinitKeyCode::Digit7 => KeyCode::Num7,
        WinitKeyCode::Digit8 => KeyCode::Num8,
        WinitKeyCode::Digit9 => KeyCode::Num9,
        WinitKeyCode::KeyA => KeyCode::A,
        WinitKeyCode::KeyB => KeyCode::B,
        WinitKeyCode::KeyC => KeyCode::C,
        WinitKeyCode::KeyD => KeyCode::D,
        WinitKeyCode::Enter | WinitKeyCode::NumpadEnter => KeyCode::Enter,
        WinitKeyCode::KeyF => KeyCode::F,
        WinitKeyCode::F1 => KeyCode::F1,
        WinitKeyCode::KeyG => KeyCode::G,
        WinitKeyCode::KeyI => KeyCode::I,
        WinitKeyCode::KeyL => KeyCode::L,
        WinitKeyCode::KeyM => KeyCode::M,
        WinitKeyCode::KeyN => KeyCode::N,
        WinitKeyCode::BracketLeft => KeyCode::OpenBracket,
        WinitKeyCode::BracketRight => KeyCode::CloseBracket,
        WinitKeyCode::KeyP => KeyCode::P,
        WinitKeyCode::Quote => KeyCode::Quote,
        WinitKeyCode::KeyR => KeyCode::R,
        WinitKeyCode::KeyS => KeyCode::S,
        WinitKeyCode::Slash => KeyCode::Slash,
        WinitKeyCode::Backslash => KeyCode::Backslash,
        WinitKeyCode::KeyT => KeyCode::T,
        WinitKeyCode::KeyU => KeyCode::U,
        WinitKeyCode::KeyW => KeyCode::W,
        WinitKeyCode::KeyX => KeyCode::X,
        WinitKeyCode::KeyY => KeyCode::Y,
        WinitKeyCode::KeyZ => KeyCode::Z,
        WinitKeyCode::ArrowLeft => KeyCode::ArrowLeft,
        WinitKeyCode::ArrowRight => KeyCode::ArrowRight,
        WinitKeyCode::ArrowUp => KeyCode::ArrowUp,
        WinitKeyCode::ArrowDown => KeyCode::ArrowDown,
        _ => return None,
    })
}

/// Convert a backend-agnostic key code back to `egui` for transitional input handling.
pub(crate) fn egui_key_from_code(key: KeyCode) -> egui::Key {
    match key {
        KeyCode::Num0 => egui::Key::Num0,
        KeyCode::Num1 => egui::Key::Num1,
        KeyCode::Num2 => egui::Key::Num2,
        KeyCode::Num3 => egui::Key::Num3,
        KeyCode::Num4 => egui::Key::Num4,
        KeyCode::Num5 => egui::Key::Num5,
        KeyCode::Num6 => egui::Key::Num6,
        KeyCode::Num7 => egui::Key::Num7,
        KeyCode::Num8 => egui::Key::Num8,
        KeyCode::Num9 => egui::Key::Num9,
        KeyCode::A => egui::Key::A,
        KeyCode::B => egui::Key::B,
        KeyCode::C => egui::Key::C,
        KeyCode::D => egui::Key::D,
        KeyCode::Enter => egui::Key::Enter,
        KeyCode::F => egui::Key::F,
        KeyCode::F1 => egui::Key::F1,
        KeyCode::G => egui::Key::G,
        KeyCode::I => egui::Key::I,
        KeyCode::L => egui::Key::L,
        KeyCode::M => egui::Key::M,
        KeyCode::N => egui::Key::N,
        KeyCode::OpenBracket => egui::Key::OpenBracket,
        KeyCode::CloseBracket => egui::Key::CloseBracket,
        KeyCode::P => egui::Key::P,
        KeyCode::Quote => egui::Key::Quote,
        KeyCode::R => egui::Key::R,
        KeyCode::S => egui::Key::S,
        KeyCode::Slash => egui::Key::Slash,
        KeyCode::Backslash => egui::Key::Backslash,
        KeyCode::T => egui::Key::T,
        KeyCode::U => egui::Key::U,
        KeyCode::W => egui::Key::W,
        KeyCode::X => egui::Key::X,
        KeyCode::Y => egui::Key::Y,
        KeyCode::Z => egui::Key::Z,
        KeyCode::ArrowLeft => egui::Key::ArrowLeft,
        KeyCode::ArrowRight => egui::Key::ArrowRight,
        KeyCode::ArrowUp => egui::Key::ArrowUp,
        KeyCode::ArrowDown => egui::Key::ArrowDown,
    }
}
