use super::*;

#[test]
fn save_interaction_and_waveform_controls_round_trip() {
    let fixture = settings_round_trip_fixture();

    assert_eq!(
        fixture.actual.core.controls.invert_waveform_scroll,
        fixture.expected.core.controls.invert_waveform_scroll
    );
    assert_eq!(
        fixture.actual.core.controls.waveform_scroll_speed,
        fixture.expected.core.controls.waveform_scroll_speed
    );
    assert_eq!(
        fixture.actual.core.controls.wheel_zoom_factor,
        fixture.expected.core.controls.wheel_zoom_factor
    );
    assert_eq!(
        fixture.actual.core.controls.keyboard_zoom_factor,
        fixture.expected.core.controls.keyboard_zoom_factor
    );
    assert_eq!(
        fixture.actual.core.controls.anti_clip_fade_enabled,
        fixture.expected.core.controls.anti_clip_fade_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.anti_clip_fade_ms,
        fixture.expected.core.controls.anti_clip_fade_ms
    );
    assert_eq!(
        fixture
            .actual
            .core
            .controls
            .auto_edge_fades_on_selection_exports,
        fixture
            .expected
            .core
            .controls
            .auto_edge_fades_on_selection_exports
    );
    assert_eq!(
        fixture.actual.core.controls.destructive_yolo_mode,
        fixture.expected.core.controls.destructive_yolo_mode
    );
    assert_eq!(
        fixture.actual.core.controls.waveform_channel_view,
        fixture.expected.core.controls.waveform_channel_view
    );
    assert_eq!(
        fixture.actual.core.controls.bpm_snap_enabled,
        fixture.expected.core.controls.bpm_snap_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.relative_bpm_grid_enabled,
        fixture.expected.core.controls.relative_bpm_grid_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.bpm_lock_enabled,
        fixture.expected.core.controls.bpm_lock_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.bpm_stretch_enabled,
        fixture.expected.core.controls.bpm_stretch_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.bpm_value,
        fixture.expected.core.controls.bpm_value
    );
    assert_eq!(
        fixture.actual.core.controls.transient_snap_enabled,
        fixture.expected.core.controls.transient_snap_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.transient_markers_enabled,
        fixture.expected.core.controls.transient_markers_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.input_monitoring_enabled,
        fixture.expected.core.controls.input_monitoring_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.normalized_audition_enabled,
        fixture.expected.core.controls.normalized_audition_enabled
    );
    assert_eq!(
        fixture.actual.core.controls.advance_after_rating,
        fixture.expected.core.controls.advance_after_rating
    );
    assert_eq!(
        fixture.actual.core.controls.rating_decay_weeks,
        fixture.expected.core.controls.rating_decay_weeks
    );
    assert_eq!(
        fixture.actual.core.controls.tooltip_mode,
        fixture.expected.core.controls.tooltip_mode
    );
    assert_eq!(
        fixture.actual.core.controls.loop_lock_enabled,
        fixture.expected.core.controls.loop_lock_enabled
    );
}
