#!/usr/bin/env python3
"""Lock startup-first-paint threshold recommendations into an env file."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_KEYS = (
    "warn_first_present_ms",
    "fail_first_present_ms",
    "warn_first_present_spread_ms",
    "fail_first_present_spread_ms",
)


@dataclass(frozen=True)
class Recommendations:
    """Parsed startup threshold recommendation values."""

    warn_first_present_ms: int
    fail_first_present_ms: int
    warn_first_present_spread_ms: int
    fail_first_present_spread_ms: int

    @classmethod
    def from_payload(cls, payload: dict[str, object]) -> "Recommendations":
        """Build recommendations from startup-summary payload values."""
        try:
            return cls(
                warn_first_present_ms=int(payload["warn_first_present_ms"]),
                fail_first_present_ms=int(payload["fail_first_present_ms"]),
                warn_first_present_spread_ms=int(payload["warn_first_present_spread_ms"]),
                fail_first_present_spread_ms=int(payload["fail_first_present_spread_ms"]),
            )
        except (KeyError, TypeError, ValueError) as exc:
            missing = [key for key in REQUIRED_KEYS if key not in payload]
            if missing:
                raise ValueError(
                    "startup summary is missing required recommendation keys: "
                    + ", ".join(missing)
                ) from exc
            raise ValueError("startup summary recommendations contain invalid values") from exc


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for threshold-lock output."""
    parser = argparse.ArgumentParser(
        description=(
            "Read startup summary JSON from scripts/perf_startup_summary.py and "
            "write startup threshold env assignments."
        )
    )
    parser.add_argument(
        "--summary",
        required=True,
        help="Path to startup summary JSON (for example target/perf/bench.startup_summary.json).",
    )
    parser.add_argument(
        "--out",
        required=True,
        help="Output env file path to write threshold assignments.",
    )
    parser.add_argument(
        "--min-valid-runs",
        type=int,
        default=3,
        help="Minimum startup runs with profile data required before writing output.",
    )
    return parser.parse_args()


def load_summary(path: Path) -> dict[str, object]:
    """Load and parse one startup summary JSON payload."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise RuntimeError(f"failed to read startup summary {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"failed to parse startup summary JSON {path}: {exc}") from exc


def validate_summary(payload: dict[str, object], min_valid_runs: int) -> Recommendations:
    """Validate summary readiness and return parsed threshold recommendations."""
    runs_with_profile_raw = payload.get("runs_with_profile", 0)
    try:
        runs_with_profile = int(runs_with_profile_raw)
    except (TypeError, ValueError) as exc:
        raise RuntimeError("startup summary `runs_with_profile` is not an integer") from exc
    if runs_with_profile < min_valid_runs:
        raise RuntimeError(
            "startup summary has insufficient valid runs: "
            f"{runs_with_profile} < {min_valid_runs}"
        )
    recommendations_payload = payload.get("recommended_thresholds_ms")
    if not isinstance(recommendations_payload, dict):
        raise RuntimeError("startup summary does not contain `recommended_thresholds_ms`")
    try:
        return Recommendations.from_payload(recommendations_payload)
    except ValueError as exc:
        raise RuntimeError(str(exc)) from exc


def render_env(summary_path: Path, recommendations: Recommendations) -> str:
    """Render env assignments for startup thresholds."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Generated by scripts/perf_startup_lock_thresholds.py from {summary_path}",
        f"# Generated at (UTC): {generated_at}",
        "# shellcheck shell=bash",
        (
            ': "${SEMPAL_PERF_WARN_STARTUP_FIRST_PRESENT_MS:='
            f"{recommendations.warn_first_present_ms}" '}"'
        ),
        "export SEMPAL_PERF_WARN_STARTUP_FIRST_PRESENT_MS",
        (
            ': "${SEMPAL_PERF_FAIL_STARTUP_FIRST_PRESENT_MS:='
            f"{recommendations.fail_first_present_ms}" '}"'
        ),
        "export SEMPAL_PERF_FAIL_STARTUP_FIRST_PRESENT_MS",
        (
            ': "${SEMPAL_PERF_WARN_STARTUP_FIRST_PRESENT_SPREAD_MS:='
            f"{recommendations.warn_first_present_spread_ms}" '}"'
        ),
        "export SEMPAL_PERF_WARN_STARTUP_FIRST_PRESENT_SPREAD_MS",
        (
            ': "${SEMPAL_PERF_FAIL_STARTUP_FIRST_PRESENT_SPREAD_MS:='
            f"{recommendations.fail_first_present_spread_ms}" '}"'
        ),
        "export SEMPAL_PERF_FAIL_STARTUP_FIRST_PRESENT_SPREAD_MS",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Entry point for startup-threshold lock helper."""
    args = parse_args()
    summary_path = Path(args.summary)
    out_path = Path(args.out)
    try:
        payload = load_summary(summary_path)
        recommendations = validate_summary(payload, args.min_valid_runs)
        rendered = render_env(summary_path, recommendations)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(rendered, encoding="utf-8")
    except RuntimeError as exc:
        print(f"[perf_guard] ERROR: {exc}", file=sys.stderr)
        return 2
    print(f"[perf_guard] startup threshold lock file written: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
